auto: false
blueCollarVersion: 1.0.0
exclude: 
  - bootstrap
  - .gitignore 
  - .gitmodules 
  - BlueCollar.sublime-project 
  - BlueCollar.sublime-workspace 
  - CNAME 
  - compile-js.py 
  - Makefile
  - yuicompressor-2.4.7.jar
pygments: true
server: true