baseurl: /
blueCollarVersion: 1.1.0
docsVersion: 1.5
exclude: 
  - bootstrap
  - static
  - .gitignore 
  - .gitmodules 
  - BlueCollar.sublime-project 
  - BlueCollar.sublime-workspace 
  - CNAME 
  - compile-js.py 
  - Makefile
  - yuicompressor-2.4.7.jar
highlighter: pygments